# pull official base image
FROM python:3.12.2-slim-bookworm

# set work directory
WORKDIR /usr/src/app
RUN mkdir /usr/src/app/staticfiles
RUN mkdir /usr/src/app/mediafiles

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get -y update \
    && apt-get install -y libpq-dev gcc
# install dependencies
# RUN pip install --upgrade pip
# # COPY ./requirements.txt .
RUN python -m venv env
# # RUN pip install -r requirements.txt