version: '3.8'

services:
  web:
    container_name: firstpy
    build:
      context: ./docker/python
      dockerfile: ./Dockerfile-py-3-12-2-slim-bw
    command: bash -c 'usermod -o -u 1000 www-data ; groupmod -o -g 1000 www-data ; chown -R www-data:www-data /usr/src/app/;source env/bin/activate && which python && pip install -r requirements.txt && gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000'
    # python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - venv_data:/usr/src/app/env
      - static_volume:/usr/src/app/staticfiles
    # ports:
    #   - 8000:8000
    expose:
      - 8000
    env_file:
      - ./app/.env.dev
    depends_on:
      - db
  db:
    container_name: db_postgres
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - ./docker/database/postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  nginx:
    container_name: python_nginx
    build: ./docker/nginx
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./docker/nginx/log:/var/log/nginx
      - static_volume:/usr/src/app/staticfiles
volumes:
  postgres_data:
  venv_data:
    driver: local
  static_volume:
